#!/bin/bash
#	Non Param Run
sudo mysql -e "use biocore; INSERT INTO ngs_runparams (id, run_group_id, outdir, run_status, wrapper_pid, runworkflow_pid, wkey, barcode, json_parameters, run_name, run_description, owner_id, group_id, perms, date_created, date_modified, last_modified_user) VALUES (5,5,'/home/travis/build/testrun2',0,NULL,NULL,NULL,0,'{\"genomebuild\":\"mousetest,mm10\",\"spaired\":\"paired\",\"resume\":\"resume\",\"fastqc\":\"yes\",\"barcodes\":\"none\",\"submission\":\"0\",\"adapters\":\"none\",\"quality\":[{\"windowSize\":\"10\",\"requiredQuality\":\"15\",\"leading\":\"5\",\"trailing\":\"5\",\"minlen\":\"36\"}],\"trim\":[{\"5len1\":\"1\",\"3len1\":\"1\",\"5len2\":\"1\",\"3len2\":\"1\",\"trimpaired\":\"paired\"}],\"split\":\"5000000\",\"commonind\":\"rRNA,miRNA,tRNA,piRNA,snRNA\"}','Non-pipeline run','Run using non pipeline parameters',209,1,15,NOW(),NOW(),209)" -uroot
sudo mysql -e "use biocore; INSERT INTO ngs_runlist (run_id, run_group_id, sample_id, owner_id, group_id, perms, date_created, date_modified, last_modified_user) VALUES (5,5,7,209,1,15,NOW(),NOW(),209)"
#	RSEM run
sudo mysql -e "use biocore; INSERT INTO ngs_runparams (id, run_group_id, outdir, run_status, wrapper_pid, runworkflow_pid, wkey, barcode, json_parameters, run_name, run_description, owner_id, group_id, perms, date_created, date_modified, last_modified_user) VALUES (6,6,'/home/travis/build/testrun3',0,NULL,NULL,NULL,0,'{\"genomebuild\":\"mousetest,mm10\",\"spaired\":\"paired\",\"resume\":\"resume\",\"fastqc\":\"no\",\"barcodes\":\"none\",\"submission\":\"0\",\"adapters\":\"none\",\"quality\":\"none\",\"trim\":\"none\",\"split\":\"none\",\"commonind\":\"none\",\"pipeline\":[{\"Type\":\"RNASeqRSEM\",\"Params\":\"--bowtie-e 70 --bowtie-chunkmbs 100\",\"MarkDuplicates\":\"no\",\"RSeQC\":\"no\",\"NoGenomeBAM\":\"no\",\"IGVTDF\":\"no\",\"BAM2BW\":\"no\",\"ExtFactor\":\"0\",\"Custom\":\"no\",\"CustomGenomeIndex\":\"None\",\"CustomGenomeAnnotation\":\"None\"}]}','RSEM run','Run using RSEM',209,1,15,NOW(),NOW(),209)" -uroot
sudo mysql -e "use biocore; INSERT INTO ngs_runlist (run_id, run_group_id, sample_id, owner_id, group_id, perms, date_created, date_modified, last_modified_user) VALUES (6,6,7,209,1,15,NOW(),NOW(),209)"
#	Tophat2 Run
sudo mysql -e "use biocore; INSERT INTO ngs_runparams (id, run_group_id, outdir, run_status, wrapper_pid, runworkflow_pid, wkey, barcode, json_parameters, run_name, run_description, owner_id, group_id, perms, date_created, date_modified, last_modified_user) VALUES (7,7,'/home/travis/build/testrun4',0,NULL,NULL,NULL,0,'{\"genomebuild\":\"mousetest,mm10\",\"spaired\":\"paired\",\"resume\":\"resume\",\"fastqc\":\"no\",\"barcodes\":\"none\",\"submission\":\"0\",\"adapters\":\"none\",\"quality\":\"none\",\"trim\":\"none\",\"split\":\"none\",\"commonind\":\"none\",\"pipeline\":[{\"Type\":\"Tophat\",\"Params\":\"\",\"MarkDuplicates\":\"no\",\"RSeQC\":\"no\",\"CollectRnaSeqMetrics\":\"no\",\"CollectMultipleMetrics\":\"no\",\"IGVTDF\":\"no\",\"BAM2BW\":\"no\",\"ExtFactor\":\"0\",\"Custom\":\"no\",\"CustomGenomeIndex\":\"None\",\"CustomGenomeAnnotation\":\"None\"}]}','Tophat run','Run using Tophat',209,1,15,NOW(),NOW(),209)" -uroot
sudo mysql -e "use biocore; INSERT INTO ngs_runlist (run_id, run_group_id, sample_id, owner_id, group_id, perms, date_created, date_modified, last_modified_user) VALUES (7,7,7,209,1,15,NOW(),NOW(),209)"
#	Chip Run
sudo mysql -e "use biocore; INSERT INTO ngs_runparams (id, run_group_id, outdir, run_status, wrapper_pid, runworkflow_pid, wkey, barcode, json_parameters, run_name, run_description, owner_id, group_id, perms, date_created, date_modified, last_modified_user) VALUES (8,8,'/home/travis/build/testrun5',0,NULL,NULL,NULL,0,'{\"genomebuild\":\"mousetest,mm10\",\"spaired\":\"paired\",\"resume\":\"resume\",\"fastqc\":\"no\",\"barcodes\":\"none\",\"submission\":\"0\",\"adapters\":\"none\",\"quality\":\"none\",\"trim\":\"none\",\"split\":\"none\",\"commonind\":\"none\",\"pipeline\":[{\"Type\":\"ChipSeq\",\"ChipInput\":[{\"name\":\"travis_test\",\"samples\":\"example_sample_1\",\"input\":\"example_sample_1\"}],\"Params\":\"--nomodel\",\"MultiMapper\":\"1\",\"TagSize\":\"75\",\"BandWith\":\"230\",\"EffectiveGenome\":\"2700000000\",\"MarkDuplicates\":\"no\",\"CollectMultipleMetrics\":\"no\",\"IGVTDF\":\"no\",\"BAM2BW\":\"no\",\"ExtFactor\":\"0\"}]}','Tophat run','Run using ChipSeq',209,1,15,NOW(),NOW(),209)" -uroot
sudo mysql -e "use biocore; INSERT INTO ngs_runlist (run_id, run_group_id, sample_id, owner_id, group_id, perms, date_created, date_modified, last_modified_user) VALUES (8,8,7,209,1,15,NOW(),NOW(),209)"
