ALTER TABLE `biocore`.`users` 
ADD COLUMN `pass_hash` VARCHAR(100) NULL DEFAULT NULL AFTER `lab`;

CREATE TABLE `biocore`.`users_pending` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `username` VARCHAR(45) NULL DEFAULT NULL,
  `clusteruser` VARCHAR(45) NULL DEFAULT NULL,
  `name` VARCHAR(45) NULL DEFAULT NULL,
  `email` VARCHAR(45) NULL DEFAULT NULL,
  `institute` VARCHAR(45) NULL DEFAULT NULL,
  `lab` VARCHAR(45) NULL DEFAULT NULL,
  `pass_hash` VARCHAR(100) NULL DEFAULT NULL,
  `verification` VARCHAR(45) NULL DEFAULT NULL,
  PRIMARY KEY (`id`));
