ALTER TABLE `ngs_donor` 
ADD COLUMN `life_stage` VARCHAR(45) NULL DEFAULT NULL AFTER `donor`,
ADD COLUMN `age` VARCHAR(45) NULL DEFAULT NULL AFTER `life_stage`,
ADD COLUMN `sex` VARCHAR(45) NULL DEFAULT NULL AFTER `age`;

ALTER TABLE `ngs_fastq_files` 
ADD COLUMN `file_uuid` VARCHAR(100) NULL DEFAULT NULL AFTER `aws_status`,
ADD COLUMN `file_acc` VARCHAR(100) NULL DEFAULT NULL AFTER `file_uuid`;
