ALTER TABLE `ngs_donor` 
ADD COLUMN `life_stage` VARCHAR(45) NULL DEFAULT NULL AFTER `donor`,
ADD COLUMN `age` VARCHAR(45) NULL DEFAULT NULL AFTER `life_stage`,
ADD COLUMN `sex` VARCHAR(45) NULL DEFAULT NULL AFTER `age`;